package com.kleegroup.lord.ui.utilisateur.view;

import java.util.ResourceBundle;

import javax.swing.BoxLayout;

/**
 * Fenêtre d'accueil du programme.
 */
public class FrameBienvenue extends javax.swing.JPanel {

	private static final long serialVersionUID = -6525068743580621312L;
	private final ResourceBundle resourceMap=
	    ResourceBundle.getBundle("resources.FrameBienvenue");
	
	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTextArea jTextArea1;

	/** Creates new form NewJPanel. */
	public FrameBienvenue() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();


		jScrollPane1.setName("jScrollPane1"); // NOI18N

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
		jTextArea1.setName("jTextArea1"); // NOI18N
		jTextArea1.setEditable(false);
		jScrollPane1.setViewportView(jTextArea1);

		this.setLayout(new BoxLayout(this,BoxLayout.LINE_AXIS));
		
		add(jScrollPane1);

	}

}
